# 本门课用到的函数积累

本笔记用于学到的包函数积累

## Numpy包

### np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)

这个函数主要是用于标准化。
- 其中ord参数指的是使用的函数
- axis指的是返回的形状 0 列 1 行
- keepdims 指的是时候返回的时候保持形状 False的话，返回的可能不是原矩阵形状
这里看出，x是一个2行3列的numpy数组（矩阵），按照每一行进行求范数axis=1，所以这里注意，在numpy中的数组[]里面表示的是一个行向量。
可以这样记：axis指的保留行，计算的是列，keepdims指的是保持行

In [2]:
import numpy as np
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
x_norm = np.linalg.norm(x,axis=1,keepdims=True)# 默认ord为2阶函数
x_result = x/x_norm
print("x shape:",x.shape)
print("x_norm shape:",x_norm.shape)
print("x_result shape:",x_result.shape)

x shape: (2, 3)
x_norm shape: (2, 1)
x_result shape: (2, 3)


### time.process_time()  # process_time函数返回的是CPU的有效时间，不包括空闲时间

time包中常用的就是获取一段程序运算的时间，但是计算除CPU的有效时间更精准的
获取时间是以微秒计算的，乘1000才是毫秒ms

In [9]:
import time
tic = time.process_time()
i = 0
sum = 0
while(i<100000000):
    sum = sum +i *1
    i+=1
print("sum:",sum)
toc = time.process_time()
print("time result(ms):",(toc-tic)*1000)

sum: 4999999950000000
time result(ms): 13578.125


### numpy中的乘法

- 这里学习以下几个函数：
- np.dot()，求两个向量的内积  1\*n  乘 n\*1
- np.outer() , 求两个向量的外积  n\*1 乘 1\*n  得到n\*n
- np.multipy(), 一个向量对应相乘

In [11]:
import numpy as np
x = np.array([1,2])
y = np.array([3,4])
print("dot:",np.dot(x,y))
print("outer:",np.outer(x,y))
print("multiply:",np.multiply(x,y))

dot: 11
outer: [[3 4]
 [6 8]]
multiply: [3 8]


### numpy.squeeze(a, axis=None)

这个函数是从矩阵shape中，去掉维度为1的。例如一个矩阵是的shape是（5， 1），使用过这个函数后，结果为（5，）。

参数：
- a是输入的矩阵
- axis : 选择shape中的一维条目的子集。如果在shape大于1的情况下设置axis，则会引发错误。

In [ ]:
>>> x = np.array([[[0], [1], [2]]])
>>> x.shape
(1, 3, 1)
>>> np.squeeze(x).shape
(3,)
>>> np.squeeze(x, axis=(2,)).shape
(1, 3)

### np.random.seed(1)

其实就是为了设定一个种子(参数),参数值不重要，但是相同参数下生成的随机数是一样的，但是注意seed是有作用域的。

个人理解就是只要设定了同一个参数，那么这个随机出来的数都是一样的。

In [8]:
import numpy as np
np.random.seed(1) #如果不加这一句话，每次随机都是不同的值

np.random.randn(1,2)

array([[ 1.62434536, -0.61175641]])

### np.random.rand()相关函数

np.random.rand(d0,d1...,dn)
- 根据维度生成[0,1)之间的数据，注意包括0但是不包含1
- dn代表生成的维度
- 返回值为指定维度的array

np.random.randn(d0,d1,..dn)

- 返回一组样本，具有正态分布
- 其他的和上面的函数一样

np.random.randint(low,high=None,size=None,dtype='l')

- 返回随机整数，范围为[low,high)
- size为维度大小
- dtype为数据类型，默认是np.int
- high不给值的话，默认是[0,low)

In [12]:
import numpy as np
print(np.random.rand(1,2))
print(np.random.randn(1,2))
print(np.random.randint(1,5,size=5))

[[0.55868983 0.14038694]]
[[ 0.56434487 -0.56651023]]
[2 4 4 2 3]


### np.linspace()

指定间隔内返回均匀的数字，看例子

In [14]:
import numpy as np
print(np.linspace(2.0, 3.0, num=5)) #[2,3]均匀5个点
print(np.linspace(2.0, 3.0, num=5, endpoint=False))#[2,3)均匀5个点
print(np.linspace(2.0, 3.0, num=5, retstep=True))# 返回一个元组，包含步长

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


### np.c_和np.r_

- np.r_是按列连接两个矩阵，就是把两个矩阵上下相加，要求列数相等
- np.c_是按行连接两个矩阵，就是把两个矩阵左右相加，要求行数相等

In [17]:
import numpy as np
a = np.array([[1, 2, 3],[7,8,9]])
b=np.array([[4,5,6],[1,2,3]])
print(a)
print(b)
print(np.c_[a,b])
print(np.r_[a,b])

[[1 2 3]
 [7 8 9]]
[[4 5 6]
 [1 2 3]]
[[1 2 3 4 5 6]
 [7 8 9 1 2 3]]
[[1 2 3]
 [7 8 9]
 [4 5 6]
 [1 2 3]]


### np.linspace()

## Jupyter Notebook中的函数

## Python中的函数

### reshape函数中的参数

X_flatten = X.reshape(X.shape[0], -1).T      # X.T is the transpose of X
其中的这个参数-1 是一种模糊控制，即本句的意思是将Xreshape行数不变，列数无所谓的

### assert函数的应用

在开发一个程序时候，与其让它运行时崩溃，不如在它出现错误条件时就崩溃（返回错误）。这时候断言assert 就显得非常有用。


assert的语法格式：
assert expression

这等价于下面这段代码：

In [ ]:
if not expression:
    raise AssertionError

In [ ]:
if 表达式的值为 True：
    程序继续运行；
else：     # 表示式的值为 False
    程序引发 AssertionError 错误

In [20]:
age = 90 #70
wage = int(age)
assert (20<wage<80)
print("11")

AssertionError: 

isinstance(b, float) 这个函数可以判断b的类型，返回True或者False